name: Master Build

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: self-hosted

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Cache Maven resources
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: tradeshift/actions-setup-java@v1
        with:
          java-version: 1.8
          maven-version: "3.8.4"
          maven-ca-cert-b64: ${{ secrets.MTLS_CACERT }}
          maven-keystore-p12-b64: ${{ secrets.MAVEN_P12 }}
          maven-keystore-password: ${{ secrets.MAVEN_P12_PASSWORD }}
          maven-settings-b64: ${{ secrets.MAVEN_SETTINGS }}
          maven-security-settings-b64: ${{ secrets.MAVEN_SECURITY }}

      - name: Prepare Maven Release
        run: mvn -B release:prepare

      - name: Perform Maven Release
        run: mvn -B release:prepare

      - name: Git Push
        run: git push
  test:
    runs-on: self-hosted

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Cache Maven resources
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: tradeshift/actions-setup-java@v1
        with:
          java-version: 1.8
          maven-version: "3.8.4"
          maven-ca-cert-b64: ${{ secrets.MTLS_CACERT }}
          maven-keystore-p12-b64: ${{ secrets.MAVEN_P12 }}
          maven-keystore-password: ${{ secrets.MAVEN_P12_PASSWORD }}
          maven-settings-b64: ${{ secrets.MAVEN_SETTINGS }}
          maven-security-settings-b64: ${{ secrets.MAVEN_SECURITY }}

      - name: Run Maven
        run: mvn -B verify

      - name: Upload artifact (Junit, surefile report)
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: serenity
          path: "**/target/surefire-reports"

      - name: SonarQube
        uses: tradeshift/actions-sonarqube@v2
        with:
          scanner: maven
          ca-cert: ${{ secrets.MTLS_CACERT }}
          client-cert: ${{ secrets.MTLS_CERT }}
          client-key: ${{ secrets.MTLS_KEY }}
          token: ${{ secrets.SONAR_TOKEN }}
          host: "https://sonar.ts.sv"
